# Generated by Django 3.1.1 on 2020-09-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20200911_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://cdn.flipsnack.com/blog/wp-content/uploads/2018/03/09163921/Cover.png', max_length=2000),
        ),
    ]
